### ISSUE TITLE
Joomlatools Framework files not properly moved on Joomlatools Platform

### ISSUE THREAD

**Issue by raeldc** [joomlatools/joomlatools-composer#14]
We're trying to install Nooku 2.x on the Joomla Platform. It seems that the joomlatools-installer didn't move files properly. 

/libraries/koowa wasn't moved to lib/libraries/koowa
/media wasn't moved to /public/media
/administrator/manifests/files/files_koowa/script.php wasn't moved to /app/administrator/manifests/files/files_koowa/script.php

**Comment by johanjanssens** [comment]
@stevenrombauts Does this issue need further follow-ups ?

**Comment by stevenrombauts** [comment]
@johanjanssens Yes this needs to be looked at. Also, this issue should actually be in the nooku/nooku-installer repository as its related to that one. The installer there needs to get the changes ported over to add support for platform. But since we actually decided to only install reusable components with nooku-installer everything needs to be updated to support this. No time yet.

**Comment by raeldc** [comment]
@stevenrombauts, I'd like to move this to the Nooku Installer repository. But I don't have the right permissions to submit a report.

**Comment by stevenrombauts** [comment]
@raeldc No worries :) We will be consolidating the installation features into this repository anyway. Will discuss further with Johan and then we can solve it once and for all.

**Comment by johanjanssens** [comment]
@stevenrombauts We still have this one to fix ?

**Comment by stevenrombauts** [comment]
@johanjanssens Yes, this should theoretically fix itself by going back to the joomlatools composer installer instead of the nooku/installer plugin. It's on the list.

**Comment by johanjanssens** [comment]
@stevenrombauts Can we also look into fixing this one this week.

**Comment by johanjanssens** [comment]
@stevenrombauts Whats the status on this one ?

**Comment by johanjanssens** [comment]
More details: Right now only joomlatools/joomlatools-composer includes fixes to handle the new paths in the platform. Solutions to resolve this issue are:

1. Move the fixes to nooku-installer (to be forked as joomlatools-framework-installer)
2. Change the installer for the framework to joomlatools-composer instead of nooku-installer

**Comment by stevenrombauts** [comment]
No longer needed, `joomlatools-framework` can be installed through Composer on both Platform and Joomla today.
