### ISSUE TITLE
Unable to install framework on Joomlatools Platform

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-composer#39]
When trying to install `joomlatools/framework` on a Joomlatools Platform install, the following error is raised:

```
PHP Fatal error:  Class 'JDispatcher' not found in /var/www/foobar2/vendor/joomlatools/framework/code/script.php on line 11
```

**Comment by johanjanssens** [comment]
@stevenrombauts This is because JDispatcher is deprecated and platform doesn't load the legacy libraries by default. This needs to be fixed in framework by making use of JEventDispatcher and not JDispatcher.

I have committed a fix here: https://github.com/joomlatools/joomlatools-framework/issues/158
